### PR TITLE
resubmit the udid support, plus the fix of rpt_hat_tgo board name string

### PR DESCRIPTION
**Pull request by shawnchain**
resubmit the pr changes

### CODE REVIEW

**Comment by g4klx** [comment]
Can you explain what the UDID is used for? Secondly, can you not create a hex value without using the standard library? I think it would be better to not use sprintf.

**Comment by shawnchain** [comment]
just wanna to add some unique identifier to the modem, like MAC address of the device so that host program could distinguish them

**Comment by g4klx** [comment]
I am completely unconvinced about UDID and the implementation is poor. The fix for the RPT_HAT_TGO is fine though. In the three and a half years that the MMDVM has existed, the need for a UDID has never occurred.

**Comment by g4klx** [comment]
UDID support has been added to the firmware in branch M17_AX25_FM which will become the standard version soon. It is sent to the host as binary data in the new format for the version data in serial protocol version 2. I will close this PR as all of its features are now in the firnware.

**Pull request closed without merging**
