### PR TITLE
Extract the IO pins defs from IOSTM.cpp to separate files

### PR DESCRIPTION
**Pull request by shawnchain**
There're 11 board types of F4/F7 modem which has different pin definitions. I extracted them from the IOSTM.cpp file into separate files.
That's the preparation for later PRs for the new type of modem boards.

### CODE REVIEW

**Comment by g4klx** [comment]
I've merged this as you can see. Can you be on standby in case there are any problems reported on the Yahoo! group or in groups.io?

**Comment by shawnchain** [comment]
> I've merged this as you can see. Can you be on standby in case there are any problems reported on the Yahoo! group or in groups.io?

Sure, I'll fix them if any problems reported there.

**Comment by phl0** [comment]
I appreciate this PR. Just compiled F7M, RPT_Hat and F4M without problems. Functional tests still missing though. (Just don't have all variants of the boards any more) :)

**Comment by g4klx** [comment]
I'm not seeing the mode LEDs operating on my M4 board (a ZUM v0.9). Maybe a bug?

**Comment by F4FXL** [comment]
Same here DStar LED not lit on ZUM v0.9 (pi target in make file)

**Comment by F4FXL** [comment]
It seems compiling for nucleo is broken since this PR
make nucleo is failing

**Pull request merged**
