### PR TITLE
Sending idle data in second slot, DMR DMO

### PR DESCRIPTION
**Pull request by juribeparada**

### CODE REVIEW

**Comment by g4klx** [comment]
This isn't quite correct. The Color Code needs setting. See similar code in DMRTX.cpp in setColorCode()

**Comment by juribeparada** [comment]
OK, I understand, I will check

**Comment by juribeparada** [comment]
I added the setting for idle data, very similar to DMRTX.cpp. What do you think?

**Comment by g4klx** [comment]
Sorry. I did it independently. It should be the same as your code in operation though.

**Comment by juribeparada** [comment]
No problem, it was almost the same.

**Pull request closed without merging**
